### ISSUE TITLE
Autostart really working?

### ISSUE THREAD

**Issue by cyrinux** [0xFireball/PluckLockEx#10]
Hi,
First thanks for this cool program.
I have a doubt, seems there is no service or thing which start plucklockex on phone start?
I'm not android expert ...
Thx

**Comment by cyrinux** [comment]
Seems it is maybe problem with miui rom, any idea?

**Comment by tommybonobo** [comment]
I am seeing the same issue of the app not starting at boot.

Running Android 9 with December 5th 2018 security patch. On an unrooted pixel 3
