### ISSUE TITLE
Locking doesn't work with Android 9

### ISSUE THREAD

**Issue by beerisgood** [0xFireball/PluckLockEx#13]
The app doesn't lock the phone, no matter which value is configured.
Only the test button lock the phone.

I allow everything and it works before I upgrade from Android 8.1 to 9.

Running LineageOS 16 (Android 9) under OnePlus 2
Using version 1.2.0 from F-DROID

**Comment by beerisgood** [comment]
*Push*

**Comment by thrdroom** [comment]
I guess this problem is related to this one https://github.com/0xFireball/PluckLockEx/issues/12

**Comment by beerisgood** [comment]
This project looks dead, anyway if exist a alternative: https://github.com/wesaphzt/privatelock
